<div class="ctmg-user" >
    <div class="p-mgu" >
        <?php if($this->error == 1){ ?>
            <div class="alert alert-danger" role="alert"><?php echo $this->result ?></div>
        <?php }elseif($this->error == 0){ ?>
            <div class="alert alert-success" role="alert">Updated Successful</div>
        <?php } ?>
        <div class="list-news-share" >
            <div class="row" >
                <h3 class="h3" >Change Password</h3>
                <form class="form-changer-pass" action="<?php echo $this->url('report/user', array('action' => 'change-password')) ?>" method="post">
                    <div class="form-group">
                        <label for="exampleInputPassword1">Old Password</label>
                        <input type="password" class="form-control password-oder" id="password-oder" name="oldpassword">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">New Password</label>
                        <input type="password" class="form-control password-new" id="password-new" name="password">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Confirm New Password</label>
                        <input type="password" class="form-control re-pasword-new" id="re-pasword-new" name="repassword">
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-default">Change</button>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>