<?php	
	$clients = json_encode($clients);	
	$streaksID = json_encode($streaksID);	
?>

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Add Collection</h1>
    </div>               
</div>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <?php
			$form = $this->form;
			$form->setAttribute('action', $this->url('report/ketoan', array('action' => 'add-collection')));
			$form->prepare();
			echo $this->form()->openTag($form);
		?>
		<div class="body bg-gray">
			<div>
				<div class="col-md-6">
					<div class="form-group">
						<?php echo $this->formRow($form->get('client')); ?>
					</div>
				</div>	
				<div class="col-md-6">
					<div class="form-group">
						<?php echo $this->formRow($form->get('streakID')); ?>
					</div>
				</div>
				<div class="col-md-12">
					<div class="form-group">
						<?php echo $this->formRow($form->get('campaign_name')); ?>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<?php echo $this->formRow($form->get('contract')); ?>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<?php echo $this->formRow($form->get('contract_value')); ?>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<?php echo $this->formRow($form->get('collected_1')); ?>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<?php echo $this->formRow($form->get('collected_date1')); ?>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<?php echo $this->formRow($form->get('collected_2')); ?>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<?php echo $this->formRow($form->get('collected_date2')); ?>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<?php echo $this->formRow($form->get('collected_3')); ?>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<?php echo $this->formRow($form->get('collected_date3')); ?>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<?php echo $this->formRow($form->get('collected_4')); ?>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<?php echo $this->formRow($form->get('collected_date4')); ?>
					</div>
				</div>
				<div class="col-md-12">
					<div class="form-group">
						<input type="hidden" value='<?php echo $clients; ?>' id="hidden_clients" />
						<input type="hidden" value='<?php echo $streaksID; ?>' id="hidden_streaksID" />
						
						
					</div>
				</div>
				<div class="col-md-12">
					<div class="form-group" align="center">
						<button type="submit" class="btn-add btn">Add Collection</button>
					</div> 
				</div>
				
			</div>
		</div>
	
		<?php echo $this->form()->closeTag(); ?>
    </div>               
</div>
<div class="row">
    <div class="col-lg-12">
	    <table width="100%">
		    <tr>
			    <th>Cilent</th>
			    <th>Streak ID</th>
			    <th>Campaign Name</th>
			    <th>Contract</th>
			    <th>Contract Value</th>
			    <th>Collected 1</th>
			    <th>Collected 2</th>
			    <th>Collected 3</th>
			    <th>Collected 4</th>
			    <th width="5%"></th>
		    </tr>
		    <?php
			foreach($collections as $collection)
			{
				?>
				<tr>
		    		<td><?php echo $collection['client'] ?></td>	
		    		<td><?php echo $collection['streakID'] ?></td>
		    		<td><?php echo $collection['campaign_name'] ?></td>
		    		<td><?php echo $collection['contract'] ?></td>
		    		<td><?php echo $collection['contract_value'] ?></td>
		    		<td><?php echo $collection['collected_1'] ?></td>
		    		<td><?php echo $collection['collected_2'] ?></td>
		    		<td><?php echo $collection['collected_3'] ?></td>
		    		<td><?php echo $collection['collected_4'] ?></td>	
		    		<td width="5%"><a href="<?php echo $this->url('report/ketoan', array('action' => 'edit-collection','id' => $collection['id'])) ?>">Edit</a></td>	    				    		
			    </tr>
				<?php
			}    
			?>
		    
	    </table>	    
    </div>               
</div>

