
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Edit Sale</h1>
    </div>               
</div>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
	    
	    <?php if($this->error == 1){ ?>
            <div class="alert alert-danger" role="alert"><?php echo $this->result ?></div>
        <?php }elseif($this->error == 0){ ?>
            <div class="alert alert-success" role="alert">Edit Sale Successful</div>
        <?php } ?>
	    
        <?php
			$form = $this->form;
			$form->setAttribute('action', $this->url('report/sale', array('action' => 'edit-sale')));
			$form->prepare();
			echo $this->form()->openTag($form);
		?>
		<div class="body bg-gray">
			<div>
				<div class="col-md-6">
					<div class="form-group">
						<?php echo $this->formRow($form->get('position')); ?>
					</div>
				</div>	
				<div class="col-md-6">
					<div class="form-group">
						<?php echo $this->formRow($form->get('senior')); ?>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<?php echo $this->formRow($form->get('email')); ?>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<?php echo $this->formRow($form->get('fullname')); ?>
					</div>
				</div>

				<div class="col-md-12">
					<div class="form-group" align="center">
						<?php echo $this->formRow($form->get('id')); ?>	
					</div> 
				</div>				
				
				<div class="col-md-12">
					<div class="form-group" align="center">
						<button type="submit" class="btn-add btn">Edit sale</button>
					</div> 
				</div>
				
			</div>
		</div>
		<?php echo $this->form()->closeTag(); ?>
    </div>               
</div>


