<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Edit Customer</h1>
    </div>               
</div>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <?php
			$form = $this->form;
			$form->setAttribute('action', $this->url('report/ketoan', array('action' => 'edit-customer')));
			$form->prepare();
			echo $this->form()->openTag($form);
		?>
		<div class="body bg-gray">
			<div>
				<div class="col-md-6">
					<div class="form-group">
						<?php echo $this->formRow($form->get('name')); ?>
					</div>
				</div>	
				<div class="col-md-6">
					<div class="form-group">
						<?php echo $this->formRow($form->get('address')); ?>
					</div>
				</div>
				<div class="col-md-12">
					<div class="form-group">
						<?php echo $this->formRow($form->get('phone')); ?>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<?php echo $this->formRow($form->get('mst')); ?>
					</div>
				</div>								
				<div class="col-md-12">
					<div class="form-group">	
						<?php echo $this->formRow($form->get('id')); ?>											
					</div>
				</div>
				<div class="col-md-12">
					<div class="form-group" align="center">
						<button type="submit" class="btn-add btn">Edit Customer</button>
					</div> 
				</div>
				
			</div>
		</div>
	
		<?php echo $this->form()->closeTag(); ?>
    </div>               
</div>

