<?php	
	$clients = json_encode($clients);	
	$streaksID = json_encode($streaksID);	
?>
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Edit Collection</h1>
    </div>               
</div>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <?php
			$form = $this->form;
			$form->setAttribute('action', $this->url('report/ketoan', array('action' => 'edit-collection')));
			$form->prepare();
			echo $this->form()->openTag($form);
		?>
		<div class="body bg-gray">
			<div>
				<div class="col-md-6">
					<div class="form-group">
						<?php echo $this->formRow($form->get('client')); ?>
					</div>
				</div>	
				<div class="col-md-6">
					<div class="form-group">
						<?php echo $this->formRow($form->get('streakID')); ?>
					</div>
				</div>
				<div class="col-md-12">
					<div class="form-group">
						<?php echo $this->formRow($form->get('campaign_name')); ?>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<?php echo $this->formRow($form->get('contract')); ?>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<?php echo $this->formRow($form->get('contract_value')); ?>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<?php echo $this->formRow($form->get('collected_1')); ?>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<?php echo $this->formRow($form->get('collected_date1')); ?>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<?php echo $this->formRow($form->get('collected_2')); ?>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<?php echo $this->formRow($form->get('collected_date2')); ?>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<?php echo $this->formRow($form->get('collected_3')); ?>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<?php echo $this->formRow($form->get('collected_date3')); ?>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<?php echo $this->formRow($form->get('collected_4')); ?>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<?php echo $this->formRow($form->get('collected_date4')); ?>
					</div>
				</div>				
				<div class="col-md-12">
					<div class="form-group">	
						<?php echo $this->formRow($form->get('id')); ?>					
						<input type="hidden" value='<?php echo $clients; ?>' id="hidden_clients" />
						<input type="hidden" value='<?php echo $streaksID; ?>' id="hidden_streaksID" />
					</div>
				</div>
				<div class="col-md-12">
					<div class="form-group" align="center">
						<button type="submit" class="btn-add btn">Edit Collection</button>
					</div> 
				</div>
				
			</div>
		</div>
	
		<?php echo $this->form()->closeTag(); ?>
    </div>               
</div>

