<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Add Media</h1>
    </div>               
</div>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
	    
	    <?php if($this->error == 1){ ?>
            <div class="alert alert-danger" role="alert"><?php echo $this->result ?></div>
        <?php }elseif($this->error == 0){ ?>
            <div class="alert alert-success" role="alert">Add Media Successful</div>
        <?php } ?>
	    
        <?php
			$form = $this->form;
			$form->setAttribute('action', $this->url('report/media', array('action' => 'add-media')));
			$form->prepare();
			echo $this->form()->openTag($form);
		?>
		<div class="body bg-gray">
			<div>
				<div class="col-md-6">
					<div class="form-group">
						<?php echo $this->formRow($form->get('position')); ?>
					</div>
				</div>	
				<div class="col-md-6">
					<div class="form-group">
						<?php echo $this->formRow($form->get('senior')); ?>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<?php echo $this->formRow($form->get('email')); ?>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<?php echo $this->formRow($form->get('fullname')); ?>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<?php echo $this->formRow($form->get('password')); ?>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<?php echo $this->formRow($form->get('confirm-password')); ?>
					</div>
				</div>
								
				
				<div class="col-md-12">
					<div class="form-group" align="center">
						<button type="submit" class="btn-add btn">Add Media</button>
					</div> 
				</div>
				
			</div>
		</div>
		<?php echo $this->form()->closeTag(); ?>
    </div>               
</div>
<div class="row">
    <div class="col-lg-12">
	    <table width="100%">
		    <tr>
			    <th>Leader</th>
			    <th>Fullname</th>
			    <th>Email</th>	
			    <th>Position</th>		    
			    <th width="5%"></th>
		    </tr>
		    <?php
			    //var_dump($users);
			   
			foreach($users as $user)
			{
				if($user['position'] != "admin")
				{
				?>
				<tr>
		    		<td><?php echo $user['leader'] ?></td>	
		    		<td><?php echo $user['fullname'] ?></td>
		    		<td><?php echo $user['email'] ?></td>
		    		<td><?php echo $user['position'] ?></td>		    			
		    		<td width="5%"><a href="<?php echo $this->url('report/media', array('action' => 'edit-media','id' => $user['id'])) ?>">Edit</a></td>	    				    		
			    </tr>
				<?php
				}
			}    
		
			?>
		    
	    </table>	    
    </div>               
</div>

