<?php
$url_ajax = $this->url(MODULE_NAME, array('action'=>'total-commission-media','controller'=>CONTROLLER_NAME));

$month_include_data = array();
$array_year = array();
$array_year1 = array();

foreach($months as $data)
{	
			
	$array_data = explode("-", $data['date']);
	
	$year = $array_data[0];
	
	if(!in_array($year, $array_year))
	{		
		$array_year[] = $year;			
		
	}
			
}
foreach($array_year as $value)
{
	
	foreach($months as $data)
	{
		$array_data = explode("-", $data['date']);
		
		$year = $array_data[0];
		$month = $array_data[1];
		
		if($month > 0 && $month < 13)
		{
			
			$temp_month_current =  $value."-".$month;
			
				if($year == $value)
				{
					
					
					if(!in_array($month, $month_include_data[$value]))
					{	
													
						$month_include_data[$value][] = $month;		
						sort($month_include_data[$value]);
					}
					
					
				}
		}
	}
}

?>

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Comission Media</h1>
    </div>               
</div>
       
<div class="row">
	
	
	
	<div class="col-lg-12">
		
					<?php													
					foreach ($month_include_data as $key => $value)
					{						
						?>						
						<span style="font-size: 20px;">Năm <?php echo $key ?></span>
						<br/>
							<ul class="ul-month">								
								<?php								
								foreach ($value as $key2 => $value2)	
								{
									
								?>
								<li class="li-month" style="float:left;padding: 5px;">	
									
									<a class="a-filter-date"  href="#" id="<?php echo $key."-".$value2 ?>">Tháng <?php echo $value2 ?></a>

								</li>
								<?php
									
								}	
								?>								
							</ul>
																								
							<div style="clear: both"></div>						
						<?php					
					}
					?>
					
					<br/><br/>
					<button href="javascript:void(0);" onclick="return exportFile()" id="btn-select-column">Export</button>
	</div>
		
     <div class="col-lg-12" style="margin-top: 20px;">    	     
		<div class="table-show">	
							
		</div>
     </div>	
     
</div>
        

